---
# 1. 디렉토리 생성 및 권한 설정 (가장 중요!)
- name: 프로메테우스 및 그라파나 데이터 디렉토리 생성
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: '0755'
  loop:
    - { path: '/etc/prometheus', owner: 'root' }
    - { path: '/home/vagrant/prometheus_data', owner: '65534' } # 프로메테우스 유저
    - { path: '/home/vagrant/grafana_data', owner: '472' }      # 그라파나 유저

# 2. 설정 파일 배포
- name: 프로메테우스 설정 파일 복사
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

# 3. 프로메테우스 컨테이너 실행 (Remote Write 수신 활성화)
- name: 프로메테우스 컨테이너 실행
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    etc_hosts:
      host.docker.internal: "host-gateway"
    restart_policy: always
    recreate: yes
    ports:
      - "9090:9090"
    volumes:
      - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/home/vagrant/prometheus_data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"  # <--- 외부에서 데이터를 받기 위한 핵심 옵션!

# 4. 그라파나 컨테이너 실행
- name: 그라파나 컨테이너 실행
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - "3000:3000"
    volumes:
      - "/home/vagrant/grafana_data:/var/lib/grafana"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "admin"

- name: 노드 익스포터(Node Exporter) 컨테이너 실행
  docker_container:
    name: node-exporter
    image: prom/node-exporter:latest
    state: started
    restart_policy: always
    # [핵심] 호스트의 네트워크를 그대로 사용해야 호스트 IP로 접근이 가능합니다.
    network_mode: host
    pid_mode: host
    volumes:
      # 호스트의 시스템 지표를 읽기 위해 읽기 전용으로 마운트합니다.
      - "/:/host:ro,rslave"
    command:
      - '--path.rootfs=/host'